---

apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    #This is where kanico is pulling from (could be from just about any source aka context -- so it will clone repo for us)
          #Where to find source code and dockerfill
    args: ["--context=git://github.com/spencerstok/kaniko-demo",
            "--destination=b0tm4n/devops-toolkit:1.0.0"]
            #This will be publishing to destination (docker or possibly harbor here)
    volumeMounts:
      #Mounting kanico-secret
      - name: kaniko-secret
        #this is mounted inside the container with this path
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json

